{% set name = "eo-tides" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eo_tides-{{ version }}.tar.gz
  sha256: d1d1f55db5424c2ef774bc9e359ed874ce70a9513521d3d39c137aae2357ab01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - colorama >=0.4.3
    - dask-core >=2023.1.0
    - geopandas >=0.10.0
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0
    - odc-geo >=0.4.7
    - odc-stac >=0.3.8
    - pandas >=2.2.0
    - psutil >=5.8.0
    - pyogrio >=0.10.0
    - pyproj >=3.7.0
    - pytmd >=2.2.7
    - scikit-learn >=1.4.0
    - scipy >=1.14.1
    - shapely >=2.0.6
    - timescale >=0.0.3
    - tqdm >=4.55.0
    - xarray >=2022.3.0
    - planetary-computer

test:
  imports:
    - eo_tides
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/eo-tides/
  summary: Tide modelling tools for large-scale satellite earth observation analysis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
